version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: parkeasy-local
      POSTGRES_USER: parkeasy
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
