-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "app_fees" INTEGER,
ADD COLUMN     "charge" JSONB,
ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
